### ISSUE TITLE
feature request: save watchdog service timestamp as epoch and in /tmp/

### ISSUE THREAD

**Issue by MichaelSjogren** [axians/microservicebus-py#39]
Hey it would be easier for us to work with if the timestamp was saved like so:
```python
import time
ts = str(int(time.time()))
with open(...) as f:
    f.write(ts)
```
And also preferablly the timestamp is saved in ram. i.e `/tmp/msb.pid`
The reason for this is to reduce the amount of wear and tear we do to our flash memory.

**Comment by wmmihaa** [comment]
Kan you test by updating the code on your end and send me the watchdog_service.py file? or just do a PR... ;)

**Comment by MichaelSjogren** [comment]
Sure!

**Comment by wmmihaa** [comment]
https://github.com/axians/microservicebus-py/releases/tag/1.0.1
